---
version: '3'

services:
  server:
    expose:
      - 7000
    image: "registry.gitlab.com/tbremer/docker-registry/mimetyp.es/server:latest"
    build:
      context: "./"
      dockerfile: "./Dockerfile"
